# -*- coding: utf-8 -*-
"""SocialMediaDataAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W2xdCiLNQZhNZ1e9OCoxZzb25MSAKKNI

1. Importing Libraries¶
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

"""2.Loading the dataset:

"""

from google.colab import files
files.upload()

#Read File:
df = pd.read_csv("social_media_engagement.csv")

#Verifying if the data is loaded correctly:
df.head()

# Number of records
n = 500

# Categories
categories = [
    "Food", "Travel", "Fashion", "Fitness",
    "Music", "Culture", "Family", "Health"
]

# Generate random data
data = {
    "Date": pd.date_range(start="2021-01-01", periods=n),
    "Category": [random.choice(categories) for _ in range(n)],
    "Likes": np.random.randint(0, 10000, size=n)
}

"""Task 2 – Generate Random Social Media Data"""

print("\nData Info:\n", df.info)

df.describe()

""" Data Scrubbing:
 1 .Cleaning and analyzising Replaces missing (NaN) values in each column
"""

# Check missing values
print(df.isnull().sum())
# Option 2: Fill missing values (example: fill numeric with 0, categorical with mode)
df["likes"] = df["likes"].fillna(0)
df["comments"] = df["comments"].fillna(0)
df["shares"] = df["shares"].fillna(0)


# Option 1: Drop rows with missing values
df = df.dropna()
for col in ["platform", "post_type", "post_day", "sentiment_score"]:
    df[col] = df[col].fillna(df[col].mode()[0])

"""2 Checking Duplicate values:

"""

# Check duplicates
print("Duplicate rows:", df.duplicated().sum())

# Remove duplicates
df = df.drop_duplicates()

"""
3. **Data** Exploration
Flatform for sentimental analysis as like comment and shares
"""

#Summary of engagement at each platform:

summary_platform = df.groupby("platform")[["likes", "comments", "shares"]].mean().round(3) #mean is rounded with three decimal points

summary_platform

#Summary of engagement by post type:

summary_post_type = df.groupby("post_type")[["likes", "comments", "shares"]].mean().round(3) #mean is rounded with three decimal points


summary_post_type

"""Social media platforms (e.g., Instagram, Twitter/X, Facebook) perform differently."""

# Create engagement column
df["engagement"] = df["likes"] + df["comments"] + df["shares"]

# Average engagement per platform
engagement_platform = df.groupby("platform")["engagement"].mean().round(2) #mean is rounded with two decimal points

engagement_platform

"""
Interpretation (Visualization of the data)"""

# Create pie chart
plt.figure(figsize=(7, 7))
plt.pie(
    engagement_platform,
    labels=engagement_platform.index,
    autopct='%1.1f%%',
    startangle=140
)

plt.title("Average Engagement by Platform")
plt.show()

# 1️⃣ Average engagement per day per platform
daily_engagement = df.groupby(["post_day", "platform"])["engagement"].mean().reset_index()

# 2️⃣ Total average engagement per day (all platforms)
# Total engagement per day (sum instead of mean)
total_engagement = df.groupby("post_day")["engagement"].sum().reset_index()
total_engagement["platform"] = "Total"

# Combine with platform data
plot_data = pd.concat([daily_engagement, total_engagement], ignore_index=True)

# 3️⃣ Combine the two for plotting
plot_data = pd.concat([daily_engagement, total_engagement], ignore_index=True)

# 4️⃣ Plot grouped bar chart
plt.figure(figsize=(12, 6))
sns.barplot(
    x="post_day",
    y="engagement",
    hue="platform",
    data=plot_data,
    order=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]  # Optional for sorting days
)

plt.title("Average Engagement by Day and Platform (Including Total)")
plt.xlabel("Day of the Week")
plt.ylabel("Average Engagement")
plt.legend(title="Platform")
plt.show()

"""# 1. CREATE the missing variable by counting posts for each day

"""

posts_per_day = df["post_day"].value_counts().reset_index()
posts_per_day.columns = ["post_day", "num_posts"]

plt.figure(figsize=(8,5))
sns.barplot(x="post_day", y="num_posts", data=posts_per_day,
            order=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"])
plt.title("Number of Posts Per Day")
plt.xlabel("Day of the Week")
plt.ylabel("Number of Posts")
plt.show()

# 1. Make sure post_time is a datetime object
df["post_time"] = pd.to_datetime(df["post_time"])

# 2. CREATE the 'hour' column (This is the missing step!)
df["hour"] = df["post_time"].dt.hour

# 3. Now the groupby will work because 'hour' exists
engagement_hour = df.groupby("hour")["engagement"].mean()

# 1. Prepare the data
# We calculate both the average engagement and the count of posts per hour
hourly_data = df.groupby("hour")["engagement"].agg(["mean", "count"]).reset_index()

# 2. Set up the figure and the first axis (Volume)
fig, ax1 = plt.subplots(figsize=(12, 6))

# Plot "Number of Posts" as bars
sns.barplot(x="hour", y="count", data=hourly_data, color="skyblue", alpha=0.6, ax=ax1)
ax1.set_xlabel("Hour of Day (24h format)")
ax1.set_ylabel("Number of Posts", color="skyblue")
ax1.tick_params(axis='y', labelcolor="skyblue")

# 3. Create the second axis (Engagement)
ax2 = ax1.twinx()  # This creates a shared X-axis
sns.lineplot(x=ax1.get_xticks(), y=hourly_data["mean"], marker="o", color="darkred", ax=ax2)
ax2.set_ylabel("Average Engagement", color="darkred")
ax2.tick_params(axis='y', labelcolor="darkred")

plt.title("Volume of Posts vs. Average Engagement by Hour")
plt.grid(axis='y', linestyle='--', alpha=0.3)
plt.show()

sns.boxplot(data=df, x="post_type", y="engagement", hue="post_type")
plt.title("Engagement Distribution by Post Type")
plt.xticks(rotation=45)
plt.show()

"""Group by Sentiment"""

sns.barplot(
    data=df,
    x="sentiment_score",
    y="engagement",
    hue="sentiment_score",  # Added this
    palette="coolwarm",
    capsize=.1,
    legend=False            # Added this to hide the redundant legend
)

plt.title("Average Engagement by Sentiment Type")
plt.xlabel("Sentiment Category")
plt.ylabel("Avg Engagement")
plt.show()

"""Co relation of likes share comment as engagement"""

# 1. Select only the numeric columns you want to compare
metrics = df[['likes', 'shares', 'comments', 'engagement']]

# 2. Calculate the correlation matrix
corr_matrix = metrics.corr()

# 3. Create the heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(corr_matrix, annot=True, cmap='RdYlGn', center=0, fmt=".2f")

plt.title("Correlation: Likes vs. Shares vs. Comments")
plt.show()

"""highest engagement post"""

# Force engagement to be numeric and remove any "units" or text
df["engagement"] = pd.to_numeric(df["engagement"].astype(str).str.replace(r'[^\d.]', '', regex=True), errors='coerce')

# Now your nlargest code will run perfectly
top_posts = df.nlargest(5, "engagement")[["post_id","platform","post_type","engagement"]]
print(top_posts)

df["month"] = df["post_time"].dt.to_period("M")

engagement_month = df.groupby("month")["engagement"].mean()
engagement_month.plot(kind="line", marker="o", title="Engagement Trend Over Time")
plt.ylabel("Avg Engagement")
plt.show()

# 1. Clean data (handling potential CSV unit/space errors)
df.columns = df.columns.str.strip()
df['engagement'] = pd.to_numeric(df['engagement'].astype(str).str.replace(r'[^\d.]', '', regex=True), errors='coerce')

# 2. Create a Pivot Table: Platforms vs Post Types
# We calculate the mean engagement for every possible combination
pivot_table = df.pivot_table(
    index='post_type',
    columns='platform',
    values='engagement',
    aggfunc='mean'
).fillna(0) # Fills empty combinations with 0

# 3. Plot Advanced Heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(pivot_table, annot=True, fmt=".0f", cmap="YlGnBu", cbar_kws={'label': 'Average Engagement'})

plt.title("Advanced Strategy Matrix: Engagement by Type & Platform", fontsize=14)
plt.show()

print(df.columns.tolist())

# 1. Select your metric columns
cols_to_fix = ['likes', 'comments', 'shares', 'engagement']

for col in cols_to_fix:
    # Force to string -> strip whitespace -> remove non-numbers -> convert to float
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(r'[^\d.]', '', regex=True) # Removes everything except numbers and dots
        .replace('', '0')                       # Replace empty strings with 0
    )
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

# 2. Check the result
print(df[cols_to_fix].dtypes)
print(df[cols_to_fix].head())

import matplotlib.pyplot as plt

# Count each post_type
post_type_counts = df["post_type"].value_counts()

# Pie chart
plt.figure(figsize=(6,6))
plt.pie(
    post_type_counts,
    labels=post_type_counts.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=plt.cm.Paired.colors
)
plt.title("Contribution of Post Types")
plt.show()

post_type_engagement = df.groupby("post_type")["engagement"].sum()

plt.figure(figsize=(6,6))
plt.pie(
    post_type_engagement,
    labels=post_type_engagement.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=plt.cm.Set3.colors
)
plt.title("Contribution of Post Types (by Engagement)")
plt.show()

"""Reports"""

# 1. Fix the Month column (Convert Period objects to strings)
# If 'month' is a Period object (like 2024-01), Seaborn crashes. We make it a string.
df['month'] = df['month'].astype(str)

# 2. Fix the Engagement column (Final "Nuclear" clean)
# This removes any hidden units (pcs, likes, commas) and forces it to a float
df['engagement'] = pd.to_numeric(
    df['engagement'].astype(str).str.replace(r'[^\d.]', '', regex=True),
    errors='coerce'
).fillna(0)

# 3. Re-calculate the trend with clean data
monthly_trend = df.groupby('month')['engagement'].mean().reset_index()

# 4. Now the lineplot will work
plt.figure(figsize=(10, 5))
sns.lineplot(data=monthly_trend, x='month', y='engagement', marker='o', color='teal')
plt.title("Timeline: Monthly Engagement Trend")
plt.xticks(rotation=45)
plt.show()

# 1. Create a mapping dictionary
sentiment_map = {
    'positive': 1.0,
    'neutral': 0.0,
    'negative': -1.0
}

# 2. Convert the column to lowercase (to handle 'Positive' vs 'positive') and map it
# We use .get to handle any unexpected words safely
if df['sentiment_score'].dtype == 'object':
    df['sentiment_score'] = df['sentiment_score'].str.lower().str.strip().map(sentiment_map).fillna(0)

# 3. Now run the correlation line again
correlation = df['sentiment_score'].corr(df['engagement'])
print(f"Sentiment Impact: The correlation is {correlation:.2f}")

# 2. GENERATING THE DASHBOARD
# ---------------------------
fig, axes = plt.subplots(2, 2, figsize=(18, 12))
plt.subplots_adjust(hspace=0.4)

# A. Volume: Content Mix (Pie Chart)
post_type_counts = df["post_type"].value_counts()
axes[0, 0].pie(post_type_counts, labels=post_type_counts.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette("pastel"))
axes[0, 0].set_title("Strategy Mix: What We Post")

# B. Performance: Engagement by Post Type (Bar Chart)
sns.barplot(ax=axes[0, 1], data=df, x="post_type", y="engagement", hue="post_type", palette="viridis", legend=False)
axes[0, 1].set_title("Impact: Avg Engagement by Type")

# C. Trend: Monthly Growth (Line Chart)
# Ensure month is sorted chronologically
monthly_trend = df.groupby('month')['engagement'].mean().reset_index()
sns.lineplot(ax=axes[1, 0], data=monthly_trend, x='month', y='engagement', marker='o', color='teal')
axes[1, 0].set_title("Timeline: Monthly Engagement Trend")
axes[1, 0].tick_params(axis='x', rotation=45)

# D. Efficiency: Top 5 Posts (Table-style text)
top_5 = df.nlargest(5, "engagement")[["post_id", "platform", "engagement"]]
axes[1, 1].axis('off')
axes[1, 1].text(0.1, 0.8, "🏆 Top 5 Performing Posts", fontsize=14, fontweight='bold')
y_pos = 0.6
for i, row in top_5.iterrows():
    axes[1, 1].text(0.1, y_pos, f"ID: {row['post_id']} | {row['platform']} | Score: {int(row['engagement'])}", fontsize=11)
    y_pos -= 0.12

plt.show()

# 3. EXECUTIVE SUMMARY PRINT-OUT
# ------------------------------
print(f"\n{'='*30}\nEXECUTIVE SUMMARY\n{'='*30}")
print(f"Total Audience Interactions: {int(df['engagement'].sum()):,}")
print(f"Most Effective Platform:     {df.groupby('platform')['engagement'].mean().idxmax()}")
print(f"Highest Engagement Hour:    {int(df.groupby('hour')['engagement'].mean().idxmax())}:00")
print(f"Sentiment Impact:            The correlation between sentiment and engagement is {df['sentiment_score'].corr(df['engagement']):.2f}")